/* soap51BookServiceSoapProxy.h
   Generated by wsdl2h 2.8.17r from /home/daniel/Documents/alpaca/alpaca-server/gsoap/51book.xml.origin and typemap.dat
   2014-08-06 20:40:36 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on soap51BookServiceSoapProxy.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/*
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/"
//gsoap ns1   schema namespace:	http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/*
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/*
 *                                                                            *
\******************************************************************************/


/// "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxt is a complexType.
struct ns1__getPolicyByPnrTxt
{
/// Element request of type "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtRequest.
    struct ns1__getPolicyByPnrTxtRequest*  request                        0;	///< Optional element.
};

/// "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":abstractLiantuoRequest is an abstract complexType.
struct ns1__abstractLiantuoRequest
{
/// Element agencyCode of type xs:string.
    char*                                agencyCode                     0;	///< Optional element.
/// Element sign of type xs:string.
    char*                                sign                           0;	///< Optional element.
};

/// "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtResponse is a complexType.
struct ns1__getPolicyByPnrTxtResponse
{
/// Element return of type "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtReply.
    struct ns1__getPolicyByPnrTxtReply*  return_                        0;	///< Optional element.
};

/// "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":abstractLiantuoReply is an abstract complexType.
struct ns1__abstractLiantuoReply
{
/// Element returnCode of type xs:string.
    char*                                returnCode                     0;	///< Optional element.
/// Element returnMessage of type xs:string.
    char*                                returnMessage                  0;	///< Optional element.
};

/// "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":wsPolicyData is a complexType.
struct ns1__wsPolicyData
{
/// Element airlineCode of type xs:string.
    char*                                airlineCode                    0;	///< Optional element.
/// Element arrivalExclude of type xs:string.
    char*                                arrivalExclude                 0;	///< Optional element.
/// Element comment of type xs:string.
    char*                                comment                        0;	///< Optional element.
/// Element commisionMoney of type xs:double.
    double*                              commisionMoney                 0;	///< Optional element.
/// Element commisionPoint of type xs:float.
    float*                               commisionPoint                 0;	///< Optional element.
/// Element departureExclude of type xs:string.
    char*                                departureExclude               0;	///< Optional element.
/// Element expiredDate of type xs:string.
    char*                                expiredDate                    0;	///< Optional element.
/// Element flightCourse of type xs:string.
    char*                                flightCourse                   0;	///< Optional element.
/// Element flightCycle of type xs:string.
    char*                                flightCycle                    0;	///< Optional element.
/// Element flightNoExclude of type xs:string.
    char*                                flightNoExclude                0;	///< Optional element.
/// Element flightNoIncluding of type xs:string.
    char*                                flightNoIncluding              0;	///< Optional element.
/// Element needSwitchPNR of type xs:int.
    int*                                 needSwitchPNR                  0;	///< Optional element.
/// Element param1 of type xs:string.
    char*                                param1                         0;	///< Optional element.
/// Element param2 of type xs:string.
    char*                                param2                         0;	///< Optional element.
/// Element param3 of type xs:string.
    char*                                param3                         0;	///< Optional element.
/// Element param4 of type xs:string.
    char*                                param4                         0;	///< Optional element.
/// Element policyBelongToFlag of type xs:string.
    char*                                policyBelongToFlag             0;	///< Optional element.
/// Element policyId of type xs:int.
    int*                                 policyId                       0;	///< Optional element.
/// Element policyType of type xs:string.
    char*                                policyType                     0;	///< Optional element.
/// Element printTicketExpiredDate of type xs:string.
    char*                                printTicketExpiredDate         0;	///< Optional element.
/// Element printTicketStartDate of type xs:string.
    char*                                printTicketStartDate           0;	///< Optional element.
/// Element productType of type xs:int.
    int*                                 productType                    0;	///< Optional element.
/// Element routeType of type xs:string.
    char*                                routeType                      0;	///< Optional element.
/// Element seatClass of type xs:string.
    char*                                seatClass                      0;	///< Optional element.
/// Element startDate of type xs:string.
    char*                                startDate                      0;	///< Optional element.
/// Element supplyOfficeNo of type xs:string.
    char*                                supplyOfficeNo                 0;	///< Optional element.
/// Element ticketSpeed of type xs:string.
    char*                                ticketSpeed                    0;	///< Optional element.
/// Element vtWorkTime of type xs:string.
    char*                                vtWorkTime                     0;	///< Optional element.
/// Element workTime of type xs:string.
    char*                                workTime                       0;	///< Optional element.
};

/// "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtRequest is a complexType with complexContent extension of "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":abstractLiantuoRequest.
struct ns1__getPolicyByPnrTxtRequest
{
/// INHERITED FROM ns1__abstractLiantuoRequest:
/// Element agencyCode of type xs:string.
    char*                                agencyCode                     0;	///< Optional element.
/// Element sign of type xs:string.
    char*                                sign                           0;	///< Optional element.
//  END OF INHERITED FROM ns1__abstractLiantuoRequest
/// Element allowSwitchPnr of type xs:int.
    int*                                 allowSwitchPnr                 0;	///< Optional element.
/// Element needSpePricePolicy of type xs:int.
    int*                                 needSpePricePolicy             0;	///< Optional element.
/// Element needSpeRulePolicy of type xs:int.
    int*                                 needSpeRulePolicy              0;	///< Optional element.
/// Element onlyOnWorking of type xs:int.
    int*                                 onlyOnWorking                  0;	///< Optional element.
/// Element param1 of type xs:string.
    char*                                param1                         0;	///< Optional element.
/// Element param2 of type xs:string.
    char*                                param2                         0;	///< Optional element.
/// Element param3 of type xs:string.
    char*                                param3                         0;	///< Optional element.
/// Element param4 of type xs:string.
    char*                                param4                         0;	///< Optional element.
/// Element pataTxt of type xs:string.
    char*                                pataTxt                        0;	///< Optional element.
/// Element pnrTxt of type xs:string.
    char*                                pnrTxt                         0;	///< Optional element.
};

/// "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtReply is a complexType with complexContent extension of "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":abstractLiantuoReply.
struct ns1__getPolicyByPnrTxtReply
{
/// INHERITED FROM ns1__abstractLiantuoReply:
/// Element returnCode of type xs:string.
    char*                                returnCode                     0;	///< Optional element.
/// Element returnMessage of type xs:string.
    char*                                returnMessage                  0;	///< Optional element.
//  END OF INHERITED FROM ns1__abstractLiantuoReply
/// Element param1 of type xs:string.
    char*                                param1                         0;	///< Optional element.
/// Element param2 of type xs:string.
    char*                                param2                         0;	///< Optional element.
/// Element param3 of type xs:string.
    char*                                param3                         0;	///< Optional element.
/// Element param4 of type xs:string.
    char*                                param4                         0;	///< Optional element.
/// Size of array of struct ns1__wsPolicyData* is 0..unbounded
   $int                                  __sizepolicyList               0;
/// Array struct ns1__wsPolicyData* of length 0..unbounded
    struct ns1__wsPolicyData*            policyList                     0;	///< Nillable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/*
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxt of type "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxt.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtReply of type "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtReply.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtRequest of type "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtRequest.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtResponse of type "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/":getPolicyByPnrTxtResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/*
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding 
//gsoap ns1  service type:	GetPolicyByPnrTxtService_USCORE1_USCORE0 
//gsoap ns1  service port:	http://wstest.51book.com:55779/ltips/services/getPolicyByPnrTxtService1.0 
//gsoap ns1  service namespace:	http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage GetPolicyByPnrTxtServiceImpl_1_0Service Definitions

@section GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0Service_bindings Service Bindings

  - @ref GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding

@section GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding Binding "GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding"

@section GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding_operations Operations of Binding  "GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding"

  - @ref __ns1__getPolicyByPnrTxt

@section GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding_ports Endpoints of Binding  "GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding"

  - http://wstest.51book.com:55779/ltips/services/getPolicyByPnrTxtService1.0

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getPolicyByPnrTxt                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getPolicyByPnrTxt" of service binding "GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getPolicyByPnrTxt(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct ns1__getPolicyByPnrTxt*      ns1__getPolicyByPnrTxt,
    // output parameters:
    struct ns1__getPolicyByPnrTxtResponse* ns1__getPolicyByPnrTxtResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getPolicyByPnrTxt(
    struct soap *soap,
    // input parameters:
    struct ns1__getPolicyByPnrTxt*      ns1__getPolicyByPnrTxt,
    // output parameters:
    struct ns1__getPolicyByPnrTxtResponse* ns1__getPolicyByPnrTxtResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	getPolicyByPnrTxt SOAP
//gsoap ns1  service method-style:	getPolicyByPnrTxt document
//gsoap ns1  service method-encoding:	getPolicyByPnrTxt literal
//gsoap ns1  service method-action:	getPolicyByPnrTxt ""
//gsoap ns1  service method-output-action:	getPolicyByPnrTxt Response
int __ns1__getPolicyByPnrTxt(
    struct ns1__getPolicyByPnrTxt*      ns1__getPolicyByPnrTxt,	///< Input parameter
    struct ns1__getPolicyByPnrTxtResponse* ns1__getPolicyByPnrTxtResponse	///< Output parameter
);

/**

@page GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding Binding "GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding"

@section GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding_policy_enablers Policy Enablers of Binding  "GetPolicyByPnrTxtServiceImpl_USCORE1_USCORE0ServiceSoapBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/"

  - <ns1:getPolicyByPnrTxt> (use wsdl2h option -g to auto-generate)

  - <ns1:getPolicyByPnrTxtReply> (use wsdl2h option -g to auto-generate)

  - <ns1:getPolicyByPnrTxtRequest> (use wsdl2h option -g to auto-generate)

  - <ns1:getPolicyByPnrTxtResponse> (use wsdl2h option -g to auto-generate)

*/

/* End of soap51BookServiceSoapProxy.h */
