/* soapH.h
   Generated by gSOAP 2.8.17r from soap51BookServiceSoapProxy.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#ifndef soap_write_float
#define soap_write_float(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_float(soap, data),0) || soap_put_float(soap, data, "float", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef soap_read_float
#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_double(soap, data),0) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE___ns1__getPolicyByPnrTxt
#define SOAP_TYPE___ns1__getPolicyByPnrTxt (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getPolicyByPnrTxt(struct soap*, struct __ns1__getPolicyByPnrTxt *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getPolicyByPnrTxt(struct soap*, const struct __ns1__getPolicyByPnrTxt *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getPolicyByPnrTxt(struct soap*, const char*, int, const struct __ns1__getPolicyByPnrTxt *, const char*);
SOAP_FMAC3 struct __ns1__getPolicyByPnrTxt * SOAP_FMAC4 soap_in___ns1__getPolicyByPnrTxt(struct soap*, const char*, struct __ns1__getPolicyByPnrTxt *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getPolicyByPnrTxt(struct soap*, const struct __ns1__getPolicyByPnrTxt *, const char*, const char*);

#ifndef soap_write___ns1__getPolicyByPnrTxt
#define soap_write___ns1__getPolicyByPnrTxt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getPolicyByPnrTxt(soap, data),0) || soap_put___ns1__getPolicyByPnrTxt(soap, data, "-ns1:getPolicyByPnrTxt", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getPolicyByPnrTxt * SOAP_FMAC4 soap_get___ns1__getPolicyByPnrTxt(struct soap*, struct __ns1__getPolicyByPnrTxt *, const char*, const char*);

#ifndef soap_read___ns1__getPolicyByPnrTxt
#define soap_read___ns1__getPolicyByPnrTxt(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getPolicyByPnrTxt(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__wsPolicyData
#define SOAP_TYPE_ns1__wsPolicyData (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__wsPolicyData(struct soap*, struct ns1__wsPolicyData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__wsPolicyData(struct soap*, const struct ns1__wsPolicyData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__wsPolicyData(struct soap*, const char*, int, const struct ns1__wsPolicyData *, const char*);
SOAP_FMAC3 struct ns1__wsPolicyData * SOAP_FMAC4 soap_in_ns1__wsPolicyData(struct soap*, const char*, struct ns1__wsPolicyData *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__wsPolicyData(struct soap*, const struct ns1__wsPolicyData *, const char*, const char*);

#ifndef soap_write_ns1__wsPolicyData
#define soap_write_ns1__wsPolicyData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__wsPolicyData(soap, data),0) || soap_put_ns1__wsPolicyData(soap, data, "ns1:wsPolicyData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__wsPolicyData * SOAP_FMAC4 soap_get_ns1__wsPolicyData(struct soap*, struct ns1__wsPolicyData *, const char*, const char*);

#ifndef soap_read_ns1__wsPolicyData
#define soap_read_ns1__wsPolicyData(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__wsPolicyData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__abstractLiantuoReply
#define SOAP_TYPE_ns1__abstractLiantuoReply (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__abstractLiantuoReply(struct soap*, struct ns1__abstractLiantuoReply *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__abstractLiantuoReply(struct soap*, const struct ns1__abstractLiantuoReply *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__abstractLiantuoReply(struct soap*, const char*, int, const struct ns1__abstractLiantuoReply *, const char*);
SOAP_FMAC3 struct ns1__abstractLiantuoReply * SOAP_FMAC4 soap_in_ns1__abstractLiantuoReply(struct soap*, const char*, struct ns1__abstractLiantuoReply *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__abstractLiantuoReply(struct soap*, const struct ns1__abstractLiantuoReply *, const char*, const char*);

#ifndef soap_write_ns1__abstractLiantuoReply
#define soap_write_ns1__abstractLiantuoReply(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__abstractLiantuoReply(soap, data),0) || soap_put_ns1__abstractLiantuoReply(soap, data, "ns1:abstractLiantuoReply", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__abstractLiantuoReply * SOAP_FMAC4 soap_get_ns1__abstractLiantuoReply(struct soap*, struct ns1__abstractLiantuoReply *, const char*, const char*);

#ifndef soap_read_ns1__abstractLiantuoReply
#define soap_read_ns1__abstractLiantuoReply(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__abstractLiantuoReply(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxtReply
#define SOAP_TYPE_ns1__getPolicyByPnrTxtReply (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getPolicyByPnrTxtReply(struct soap*, struct ns1__getPolicyByPnrTxtReply *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getPolicyByPnrTxtReply(struct soap*, const struct ns1__getPolicyByPnrTxtReply *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getPolicyByPnrTxtReply(struct soap*, const char*, int, const struct ns1__getPolicyByPnrTxtReply *, const char*);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxtReply * SOAP_FMAC4 soap_in_ns1__getPolicyByPnrTxtReply(struct soap*, const char*, struct ns1__getPolicyByPnrTxtReply *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getPolicyByPnrTxtReply(struct soap*, const struct ns1__getPolicyByPnrTxtReply *, const char*, const char*);

#ifndef soap_write_ns1__getPolicyByPnrTxtReply
#define soap_write_ns1__getPolicyByPnrTxtReply(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__getPolicyByPnrTxtReply(soap, data),0) || soap_put_ns1__getPolicyByPnrTxtReply(soap, data, "ns1:getPolicyByPnrTxtReply", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxtReply * SOAP_FMAC4 soap_get_ns1__getPolicyByPnrTxtReply(struct soap*, struct ns1__getPolicyByPnrTxtReply *, const char*, const char*);

#ifndef soap_read_ns1__getPolicyByPnrTxtReply
#define soap_read_ns1__getPolicyByPnrTxtReply(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getPolicyByPnrTxtReply(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxtResponse
#define SOAP_TYPE_ns1__getPolicyByPnrTxtResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getPolicyByPnrTxtResponse(struct soap*, struct ns1__getPolicyByPnrTxtResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getPolicyByPnrTxtResponse(struct soap*, const struct ns1__getPolicyByPnrTxtResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getPolicyByPnrTxtResponse(struct soap*, const char*, int, const struct ns1__getPolicyByPnrTxtResponse *, const char*);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxtResponse * SOAP_FMAC4 soap_in_ns1__getPolicyByPnrTxtResponse(struct soap*, const char*, struct ns1__getPolicyByPnrTxtResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getPolicyByPnrTxtResponse(struct soap*, const struct ns1__getPolicyByPnrTxtResponse *, const char*, const char*);

#ifndef soap_write_ns1__getPolicyByPnrTxtResponse
#define soap_write_ns1__getPolicyByPnrTxtResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__getPolicyByPnrTxtResponse(soap, data),0) || soap_put_ns1__getPolicyByPnrTxtResponse(soap, data, "ns1:getPolicyByPnrTxtResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxtResponse * SOAP_FMAC4 soap_get_ns1__getPolicyByPnrTxtResponse(struct soap*, struct ns1__getPolicyByPnrTxtResponse *, const char*, const char*);

#ifndef soap_read_ns1__getPolicyByPnrTxtResponse
#define soap_read_ns1__getPolicyByPnrTxtResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getPolicyByPnrTxtResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__abstractLiantuoRequest
#define SOAP_TYPE_ns1__abstractLiantuoRequest (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__abstractLiantuoRequest(struct soap*, struct ns1__abstractLiantuoRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__abstractLiantuoRequest(struct soap*, const struct ns1__abstractLiantuoRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__abstractLiantuoRequest(struct soap*, const char*, int, const struct ns1__abstractLiantuoRequest *, const char*);
SOAP_FMAC3 struct ns1__abstractLiantuoRequest * SOAP_FMAC4 soap_in_ns1__abstractLiantuoRequest(struct soap*, const char*, struct ns1__abstractLiantuoRequest *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__abstractLiantuoRequest(struct soap*, const struct ns1__abstractLiantuoRequest *, const char*, const char*);

#ifndef soap_write_ns1__abstractLiantuoRequest
#define soap_write_ns1__abstractLiantuoRequest(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__abstractLiantuoRequest(soap, data),0) || soap_put_ns1__abstractLiantuoRequest(soap, data, "ns1:abstractLiantuoRequest", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__abstractLiantuoRequest * SOAP_FMAC4 soap_get_ns1__abstractLiantuoRequest(struct soap*, struct ns1__abstractLiantuoRequest *, const char*, const char*);

#ifndef soap_read_ns1__abstractLiantuoRequest
#define soap_read_ns1__abstractLiantuoRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__abstractLiantuoRequest(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxtRequest
#define SOAP_TYPE_ns1__getPolicyByPnrTxtRequest (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getPolicyByPnrTxtRequest(struct soap*, struct ns1__getPolicyByPnrTxtRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getPolicyByPnrTxtRequest(struct soap*, const struct ns1__getPolicyByPnrTxtRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getPolicyByPnrTxtRequest(struct soap*, const char*, int, const struct ns1__getPolicyByPnrTxtRequest *, const char*);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxtRequest * SOAP_FMAC4 soap_in_ns1__getPolicyByPnrTxtRequest(struct soap*, const char*, struct ns1__getPolicyByPnrTxtRequest *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getPolicyByPnrTxtRequest(struct soap*, const struct ns1__getPolicyByPnrTxtRequest *, const char*, const char*);

#ifndef soap_write_ns1__getPolicyByPnrTxtRequest
#define soap_write_ns1__getPolicyByPnrTxtRequest(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__getPolicyByPnrTxtRequest(soap, data),0) || soap_put_ns1__getPolicyByPnrTxtRequest(soap, data, "ns1:getPolicyByPnrTxtRequest", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxtRequest * SOAP_FMAC4 soap_get_ns1__getPolicyByPnrTxtRequest(struct soap*, struct ns1__getPolicyByPnrTxtRequest *, const char*, const char*);

#ifndef soap_read_ns1__getPolicyByPnrTxtRequest
#define soap_read_ns1__getPolicyByPnrTxtRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getPolicyByPnrTxtRequest(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxt
#define SOAP_TYPE_ns1__getPolicyByPnrTxt (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getPolicyByPnrTxt(struct soap*, struct ns1__getPolicyByPnrTxt *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getPolicyByPnrTxt(struct soap*, const struct ns1__getPolicyByPnrTxt *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getPolicyByPnrTxt(struct soap*, const char*, int, const struct ns1__getPolicyByPnrTxt *, const char*);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxt * SOAP_FMAC4 soap_in_ns1__getPolicyByPnrTxt(struct soap*, const char*, struct ns1__getPolicyByPnrTxt *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getPolicyByPnrTxt(struct soap*, const struct ns1__getPolicyByPnrTxt *, const char*, const char*);

#ifndef soap_write_ns1__getPolicyByPnrTxt
#define soap_write_ns1__getPolicyByPnrTxt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__getPolicyByPnrTxt(soap, data),0) || soap_put_ns1__getPolicyByPnrTxt(soap, data, "ns1:getPolicyByPnrTxt", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxt * SOAP_FMAC4 soap_get_ns1__getPolicyByPnrTxt(struct soap*, struct ns1__getPolicyByPnrTxt *, const char*, const char*);

#ifndef soap_read_ns1__getPolicyByPnrTxt
#define soap_read_ns1__getPolicyByPnrTxt(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getPolicyByPnrTxt(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons1__getPolicyByPnrTxtResponse
#define SOAP_TYPE_PointerTons1__getPolicyByPnrTxtResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getPolicyByPnrTxtResponse(struct soap*, struct ns1__getPolicyByPnrTxtResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getPolicyByPnrTxtResponse(struct soap*, const char *, int, struct ns1__getPolicyByPnrTxtResponse *const*, const char *);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxtResponse ** SOAP_FMAC4 soap_in_PointerTons1__getPolicyByPnrTxtResponse(struct soap*, const char*, struct ns1__getPolicyByPnrTxtResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getPolicyByPnrTxtResponse(struct soap*, struct ns1__getPolicyByPnrTxtResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getPolicyByPnrTxtResponse
#define soap_write_PointerTons1__getPolicyByPnrTxtResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__getPolicyByPnrTxtResponse(soap, data),0) || soap_put_PointerTons1__getPolicyByPnrTxtResponse(soap, data, "ns1:getPolicyByPnrTxtResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxtResponse ** SOAP_FMAC4 soap_get_PointerTons1__getPolicyByPnrTxtResponse(struct soap*, struct ns1__getPolicyByPnrTxtResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__getPolicyByPnrTxtResponse
#define soap_read_PointerTons1__getPolicyByPnrTxtResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getPolicyByPnrTxtResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__getPolicyByPnrTxt
#define SOAP_TYPE_PointerTons1__getPolicyByPnrTxt (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getPolicyByPnrTxt(struct soap*, struct ns1__getPolicyByPnrTxt *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getPolicyByPnrTxt(struct soap*, const char *, int, struct ns1__getPolicyByPnrTxt *const*, const char *);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxt ** SOAP_FMAC4 soap_in_PointerTons1__getPolicyByPnrTxt(struct soap*, const char*, struct ns1__getPolicyByPnrTxt **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getPolicyByPnrTxt(struct soap*, struct ns1__getPolicyByPnrTxt *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getPolicyByPnrTxt
#define soap_write_PointerTons1__getPolicyByPnrTxt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__getPolicyByPnrTxt(soap, data),0) || soap_put_PointerTons1__getPolicyByPnrTxt(soap, data, "ns1:getPolicyByPnrTxt", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxt ** SOAP_FMAC4 soap_get_PointerTons1__getPolicyByPnrTxt(struct soap*, struct ns1__getPolicyByPnrTxt **, const char*, const char*);

#ifndef soap_read_PointerTons1__getPolicyByPnrTxt
#define soap_read_PointerTons1__getPolicyByPnrTxt(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getPolicyByPnrTxt(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__wsPolicyData
#define SOAP_TYPE_PointerTons1__wsPolicyData (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__wsPolicyData(struct soap*, struct ns1__wsPolicyData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__wsPolicyData(struct soap*, const char *, int, struct ns1__wsPolicyData *const*, const char *);
SOAP_FMAC3 struct ns1__wsPolicyData ** SOAP_FMAC4 soap_in_PointerTons1__wsPolicyData(struct soap*, const char*, struct ns1__wsPolicyData **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__wsPolicyData(struct soap*, struct ns1__wsPolicyData *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__wsPolicyData
#define soap_write_PointerTons1__wsPolicyData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__wsPolicyData(soap, data),0) || soap_put_PointerTons1__wsPolicyData(soap, data, "ns1:wsPolicyData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__wsPolicyData ** SOAP_FMAC4 soap_get_PointerTons1__wsPolicyData(struct soap*, struct ns1__wsPolicyData **, const char*, const char*);

#ifndef soap_read_PointerTons1__wsPolicyData
#define soap_read_PointerTons1__wsPolicyData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__wsPolicyData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data),0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTofloat
#define SOAP_TYPE_PointerTofloat (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofloat(struct soap*, float *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofloat(struct soap*, const char *, int, float *const*, const char *);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_in_PointerTofloat(struct soap*, const char*, float **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofloat(struct soap*, float *const*, const char*, const char*);

#ifndef soap_write_PointerTofloat
#define soap_write_PointerTofloat(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTofloat(soap, data),0) || soap_put_PointerTofloat(soap, data, "float", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 float ** SOAP_FMAC4 soap_get_PointerTofloat(struct soap*, float **, const char*, const char*);

#ifndef soap_read_PointerTofloat
#define soap_read_PointerTofloat(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTofloat(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTodouble
#define SOAP_TYPE_PointerTodouble (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTodouble(struct soap*, double *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTodouble(struct soap*, const char *, int, double *const*, const char *);
SOAP_FMAC3 double ** SOAP_FMAC4 soap_in_PointerTodouble(struct soap*, const char*, double **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTodouble(struct soap*, double *const*, const char*, const char*);

#ifndef soap_write_PointerTodouble
#define soap_write_PointerTodouble(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTodouble(soap, data),0) || soap_put_PointerTodouble(soap, data, "double", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 double ** SOAP_FMAC4 soap_get_PointerTodouble(struct soap*, double **, const char*, const char*);

#ifndef soap_read_PointerTodouble
#define soap_read_PointerTodouble(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTodouble(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__getPolicyByPnrTxtReply
#define SOAP_TYPE_PointerTons1__getPolicyByPnrTxtReply (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getPolicyByPnrTxtReply(struct soap*, struct ns1__getPolicyByPnrTxtReply *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getPolicyByPnrTxtReply(struct soap*, const char *, int, struct ns1__getPolicyByPnrTxtReply *const*, const char *);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxtReply ** SOAP_FMAC4 soap_in_PointerTons1__getPolicyByPnrTxtReply(struct soap*, const char*, struct ns1__getPolicyByPnrTxtReply **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getPolicyByPnrTxtReply(struct soap*, struct ns1__getPolicyByPnrTxtReply *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getPolicyByPnrTxtReply
#define soap_write_PointerTons1__getPolicyByPnrTxtReply(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__getPolicyByPnrTxtReply(soap, data),0) || soap_put_PointerTons1__getPolicyByPnrTxtReply(soap, data, "ns1:getPolicyByPnrTxtReply", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxtReply ** SOAP_FMAC4 soap_get_PointerTons1__getPolicyByPnrTxtReply(struct soap*, struct ns1__getPolicyByPnrTxtReply **, const char*, const char*);

#ifndef soap_read_PointerTons1__getPolicyByPnrTxtReply
#define soap_read_PointerTons1__getPolicyByPnrTxtReply(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getPolicyByPnrTxtReply(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__getPolicyByPnrTxtRequest
#define SOAP_TYPE_PointerTons1__getPolicyByPnrTxtRequest (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getPolicyByPnrTxtRequest(struct soap*, struct ns1__getPolicyByPnrTxtRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getPolicyByPnrTxtRequest(struct soap*, const char *, int, struct ns1__getPolicyByPnrTxtRequest *const*, const char *);
SOAP_FMAC3 struct ns1__getPolicyByPnrTxtRequest ** SOAP_FMAC4 soap_in_PointerTons1__getPolicyByPnrTxtRequest(struct soap*, const char*, struct ns1__getPolicyByPnrTxtRequest **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getPolicyByPnrTxtRequest(struct soap*, struct ns1__getPolicyByPnrTxtRequest *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getPolicyByPnrTxtRequest
#define soap_write_PointerTons1__getPolicyByPnrTxtRequest(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__getPolicyByPnrTxtRequest(soap, data),0) || soap_put_PointerTons1__getPolicyByPnrTxtRequest(soap, data, "ns1:getPolicyByPnrTxtRequest", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__getPolicyByPnrTxtRequest ** SOAP_FMAC4 soap_get_PointerTons1__getPolicyByPnrTxtRequest(struct soap*, struct ns1__getPolicyByPnrTxtRequest **, const char*, const char*);

#ifndef soap_read_PointerTons1__getPolicyByPnrTxtRequest
#define soap_read_PointerTons1__getPolicyByPnrTxtRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getPolicyByPnrTxtRequest(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
