/* soapClient.c
   Generated by gSOAP 2.8.17r from soap51BookServiceSoapProxy.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.17r 2014-08-06 20:40:55 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getPolicyByPnrTxt(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getPolicyByPnrTxt *ns1__getPolicyByPnrTxt, struct ns1__getPolicyByPnrTxtResponse *ns1__getPolicyByPnrTxtResponse)
{	struct __ns1__getPolicyByPnrTxt soap_tmp___ns1__getPolicyByPnrTxt;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://wstest.51book.com:55779/ltips/services/getPolicyByPnrTxtService1.0";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getPolicyByPnrTxt.ns1__getPolicyByPnrTxt = ns1__getPolicyByPnrTxt;
	soap_serializeheader(soap);
	soap_serialize___ns1__getPolicyByPnrTxt(soap, &soap_tmp___ns1__getPolicyByPnrTxt);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getPolicyByPnrTxt(soap, &soap_tmp___ns1__getPolicyByPnrTxt, "-ns1:getPolicyByPnrTxt", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getPolicyByPnrTxt(soap, &soap_tmp___ns1__getPolicyByPnrTxt, "-ns1:getPolicyByPnrTxt", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getPolicyByPnrTxtResponse)
		return soap_closesock(soap);
	soap_default_ns1__getPolicyByPnrTxtResponse(soap, ns1__getPolicyByPnrTxtResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getPolicyByPnrTxtResponse(soap, ns1__getPolicyByPnrTxtResponse, "ns1:getPolicyByPnrTxtResponse", "ns1:getPolicyByPnrTxtResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
