/* soapStub.h
   Generated by gSOAP 2.8.17r from soap51BookServiceSoapProxy.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20817
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxt
#define SOAP_TYPE_ns1__getPolicyByPnrTxt (7)
/* ns1:getPolicyByPnrTxt */
struct ns1__getPolicyByPnrTxt
{
	struct ns1__getPolicyByPnrTxtRequest *request;	/* optional element of type ns1:getPolicyByPnrTxtRequest */
};
#endif

#ifndef SOAP_TYPE_ns1__abstractLiantuoRequest
#define SOAP_TYPE_ns1__abstractLiantuoRequest (10)
/* ns1:abstractLiantuoRequest */
struct ns1__abstractLiantuoRequest
{
	char *agencyCode;	/* optional element of type xsd:string */
	char *sign;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxtResponse
#define SOAP_TYPE_ns1__getPolicyByPnrTxtResponse (11)
/* ns1:getPolicyByPnrTxtResponse */
struct ns1__getPolicyByPnrTxtResponse
{
	struct ns1__getPolicyByPnrTxtReply *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:getPolicyByPnrTxtReply */
};
#endif

#ifndef SOAP_TYPE_ns1__abstractLiantuoReply
#define SOAP_TYPE_ns1__abstractLiantuoReply (14)
/* ns1:abstractLiantuoReply */
struct ns1__abstractLiantuoReply
{
	char *returnCode;	/* optional element of type xsd:string */
	char *returnMessage;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__wsPolicyData
#define SOAP_TYPE_ns1__wsPolicyData (15)
/* ns1:wsPolicyData */
struct ns1__wsPolicyData
{
	char *airlineCode;	/* optional element of type xsd:string */
	char *arrivalExclude;	/* optional element of type xsd:string */
	char *comment;	/* optional element of type xsd:string */
	double *commisionMoney;	/* optional element of type xsd:double */
	float *commisionPoint;	/* optional element of type xsd:float */
	char *departureExclude;	/* optional element of type xsd:string */
	char *expiredDate;	/* optional element of type xsd:string */
	char *flightCourse;	/* optional element of type xsd:string */
	char *flightCycle;	/* optional element of type xsd:string */
	char *flightNoExclude;	/* optional element of type xsd:string */
	char *flightNoIncluding;	/* optional element of type xsd:string */
	int *needSwitchPNR;	/* optional element of type xsd:int */
	char *param1;	/* optional element of type xsd:string */
	char *param2;	/* optional element of type xsd:string */
	char *param3;	/* optional element of type xsd:string */
	char *param4;	/* optional element of type xsd:string */
	char *policyBelongToFlag;	/* optional element of type xsd:string */
	int *policyId;	/* optional element of type xsd:int */
	char *policyType;	/* optional element of type xsd:string */
	char *printTicketExpiredDate;	/* optional element of type xsd:string */
	char *printTicketStartDate;	/* optional element of type xsd:string */
	int *productType;	/* optional element of type xsd:int */
	char *routeType;	/* optional element of type xsd:string */
	char *seatClass;	/* optional element of type xsd:string */
	char *startDate;	/* optional element of type xsd:string */
	char *supplyOfficeNo;	/* optional element of type xsd:string */
	char *ticketSpeed;	/* optional element of type xsd:string */
	char *vtWorkTime;	/* optional element of type xsd:string */
	char *workTime;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxtRequest
#define SOAP_TYPE_ns1__getPolicyByPnrTxtRequest (8)
/* ns1:getPolicyByPnrTxtRequest */
struct ns1__getPolicyByPnrTxtRequest
{
	char *agencyCode;	/* optional element of type xsd:string */
	char *sign;	/* optional element of type xsd:string */
	int *allowSwitchPnr;	/* optional element of type xsd:int */
	int *needSpePricePolicy;	/* optional element of type xsd:int */
	int *needSpeRulePolicy;	/* optional element of type xsd:int */
	int *onlyOnWorking;	/* optional element of type xsd:int */
	char *param1;	/* optional element of type xsd:string */
	char *param2;	/* optional element of type xsd:string */
	char *param3;	/* optional element of type xsd:string */
	char *param4;	/* optional element of type xsd:string */
	char *pataTxt;	/* optional element of type xsd:string */
	char *pnrTxt;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getPolicyByPnrTxtReply
#define SOAP_TYPE_ns1__getPolicyByPnrTxtReply (12)
/* ns1:getPolicyByPnrTxtReply */
struct ns1__getPolicyByPnrTxtReply
{
	char *returnCode;	/* optional element of type xsd:string */
	char *returnMessage;	/* optional element of type xsd:string */
	char *param1;	/* optional element of type xsd:string */
	char *param2;	/* optional element of type xsd:string */
	char *param3;	/* optional element of type xsd:string */
	char *param4;	/* optional element of type xsd:string */
	int __sizepolicyList;	/* sequence of elements <policyList> */
	struct ns1__wsPolicyData *policyList;	/* optional element of type ns1:wsPolicyData */
};
#endif

#ifndef SOAP_TYPE___ns1__getPolicyByPnrTxt
#define SOAP_TYPE___ns1__getPolicyByPnrTxt (25)
/* Operation wrapper: */
struct __ns1__getPolicyByPnrTxt
{
	struct ns1__getPolicyByPnrTxt *ns1__getPolicyByPnrTxt;	/* optional element of type ns1:getPolicyByPnrTxt */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__getPolicyByPnrTxt(struct soap*, struct ns1__getPolicyByPnrTxt *ns1__getPolicyByPnrTxt, struct ns1__getPolicyByPnrTxtResponse *ns1__getPolicyByPnrTxtResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getPolicyByPnrTxt(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getPolicyByPnrTxt(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getPolicyByPnrTxt *ns1__getPolicyByPnrTxt, struct ns1__getPolicyByPnrTxtResponse *ns1__getPolicyByPnrTxtResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
