/* soapClient.cpp
   Generated by gSOAP 2.8.16 from webservice.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.16 2013-11-17 13:48:37 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAllCommonPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAllCommonPolicy *ns1__GetAllCommonPolicy, _ns1__GetAllCommonPolicyResponse *ns1__GetAllCommonPolicyResponse)
{	struct __ns1__GetAllCommonPolicy soap_tmp___ns1__GetAllCommonPolicy;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetAllCommonPolicy";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAllCommonPolicy.ns1__GetAllCommonPolicy = ns1__GetAllCommonPolicy;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAllCommonPolicy(soap, &soap_tmp___ns1__GetAllCommonPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAllCommonPolicy(soap, &soap_tmp___ns1__GetAllCommonPolicy, "-ns1:GetAllCommonPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAllCommonPolicy(soap, &soap_tmp___ns1__GetAllCommonPolicy, "-ns1:GetAllCommonPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAllCommonPolicyResponse)
		return soap_closesock(soap);
	ns1__GetAllCommonPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAllCommonPolicyResponse->soap_get(soap, "ns1:GetAllCommonPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAllCommonPolicyZIP(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAllCommonPolicyZIP *ns1__GetAllCommonPolicyZIP, _ns1__GetAllCommonPolicyZIPResponse *ns1__GetAllCommonPolicyZIPResponse)
{	struct __ns1__GetAllCommonPolicyZIP soap_tmp___ns1__GetAllCommonPolicyZIP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetAllCommonPolicyZIP";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAllCommonPolicyZIP.ns1__GetAllCommonPolicyZIP = ns1__GetAllCommonPolicyZIP;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAllCommonPolicyZIP(soap, &soap_tmp___ns1__GetAllCommonPolicyZIP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAllCommonPolicyZIP(soap, &soap_tmp___ns1__GetAllCommonPolicyZIP, "-ns1:GetAllCommonPolicyZIP", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAllCommonPolicyZIP(soap, &soap_tmp___ns1__GetAllCommonPolicyZIP, "-ns1:GetAllCommonPolicyZIP", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAllCommonPolicyZIPResponse)
		return soap_closesock(soap);
	ns1__GetAllCommonPolicyZIPResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAllCommonPolicyZIPResponse->soap_get(soap, "ns1:GetAllCommonPolicyZIPResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAlterCommonPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAlterCommonPolicy *ns1__GetAlterCommonPolicy, _ns1__GetAlterCommonPolicyResponse *ns1__GetAlterCommonPolicyResponse)
{	struct __ns1__GetAlterCommonPolicy soap_tmp___ns1__GetAlterCommonPolicy;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetAlterCommonPolicy";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAlterCommonPolicy.ns1__GetAlterCommonPolicy = ns1__GetAlterCommonPolicy;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAlterCommonPolicy(soap, &soap_tmp___ns1__GetAlterCommonPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAlterCommonPolicy(soap, &soap_tmp___ns1__GetAlterCommonPolicy, "-ns1:GetAlterCommonPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAlterCommonPolicy(soap, &soap_tmp___ns1__GetAlterCommonPolicy, "-ns1:GetAlterCommonPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAlterCommonPolicyResponse)
		return soap_closesock(soap);
	ns1__GetAlterCommonPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAlterCommonPolicyResponse->soap_get(soap, "ns1:GetAlterCommonPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__MatchCommonPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__MatchCommonPolicy *ns1__MatchCommonPolicy, _ns1__MatchCommonPolicyResponse *ns1__MatchCommonPolicyResponse)
{	struct __ns1__MatchCommonPolicy soap_tmp___ns1__MatchCommonPolicy;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/MatchCommonPolicy";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__MatchCommonPolicy.ns1__MatchCommonPolicy = ns1__MatchCommonPolicy;
	soap_serializeheader(soap);
	soap_serialize___ns1__MatchCommonPolicy(soap, &soap_tmp___ns1__MatchCommonPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__MatchCommonPolicy(soap, &soap_tmp___ns1__MatchCommonPolicy, "-ns1:MatchCommonPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__MatchCommonPolicy(soap, &soap_tmp___ns1__MatchCommonPolicy, "-ns1:MatchCommonPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__MatchCommonPolicyResponse)
		return soap_closesock(soap);
	ns1__MatchCommonPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__MatchCommonPolicyResponse->soap_get(soap, "ns1:MatchCommonPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAVPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAVPolicy *ns1__GetAVPolicy, _ns1__GetAVPolicyResponse *ns1__GetAVPolicyResponse)
{	struct __ns1__GetAVPolicy soap_tmp___ns1__GetAVPolicy;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetAVPolicy";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAVPolicy.ns1__GetAVPolicy = ns1__GetAVPolicy;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAVPolicy(soap, &soap_tmp___ns1__GetAVPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAVPolicy(soap, &soap_tmp___ns1__GetAVPolicy, "-ns1:GetAVPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAVPolicy(soap, &soap_tmp___ns1__GetAVPolicy, "-ns1:GetAVPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAVPolicyResponse)
		return soap_closesock(soap);
	ns1__GetAVPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAVPolicyResponse->soap_get(soap, "ns1:GetAVPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetDomesticMatchNormalZRateByID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetDomesticMatchNormalZRateByID *ns1__GetDomesticMatchNormalZRateByID, _ns1__GetDomesticMatchNormalZRateByIDResponse *ns1__GetDomesticMatchNormalZRateByIDResponse)
{	struct __ns1__GetDomesticMatchNormalZRateByID soap_tmp___ns1__GetDomesticMatchNormalZRateByID;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetDomesticMatchNormalZRateByID";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetDomesticMatchNormalZRateByID.ns1__GetDomesticMatchNormalZRateByID = ns1__GetDomesticMatchNormalZRateByID;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetDomesticMatchNormalZRateByID(soap, &soap_tmp___ns1__GetDomesticMatchNormalZRateByID);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetDomesticMatchNormalZRateByID(soap, &soap_tmp___ns1__GetDomesticMatchNormalZRateByID, "-ns1:GetDomesticMatchNormalZRateByID", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetDomesticMatchNormalZRateByID(soap, &soap_tmp___ns1__GetDomesticMatchNormalZRateByID, "-ns1:GetDomesticMatchNormalZRateByID", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetDomesticMatchNormalZRateByIDResponse)
		return soap_closesock(soap);
	ns1__GetDomesticMatchNormalZRateByIDResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetDomesticMatchNormalZRateByIDResponse->soap_get(soap, "ns1:GetDomesticMatchNormalZRateByIDResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DetailCreateOrder(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__DetailCreateOrder *ns1__DetailCreateOrder, _ns1__DetailCreateOrderResponse *ns1__DetailCreateOrderResponse)
{	struct __ns1__DetailCreateOrder soap_tmp___ns1__DetailCreateOrder;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/DetailCreateOrder";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DetailCreateOrder.ns1__DetailCreateOrder = ns1__DetailCreateOrder;
	soap_serializeheader(soap);
	soap_serialize___ns1__DetailCreateOrder(soap, &soap_tmp___ns1__DetailCreateOrder);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DetailCreateOrder(soap, &soap_tmp___ns1__DetailCreateOrder, "-ns1:DetailCreateOrder", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DetailCreateOrder(soap, &soap_tmp___ns1__DetailCreateOrder, "-ns1:DetailCreateOrder", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DetailCreateOrderResponse)
		return soap_closesock(soap);
	ns1__DetailCreateOrderResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DetailCreateOrderResponse->soap_get(soap, "ns1:DetailCreateOrderResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RTCreateOrder(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__RTCreateOrder *ns1__RTCreateOrder, _ns1__RTCreateOrderResponse *ns1__RTCreateOrderResponse)
{	struct __ns1__RTCreateOrder soap_tmp___ns1__RTCreateOrder;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/RTCreateOrder";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RTCreateOrder.ns1__RTCreateOrder = ns1__RTCreateOrder;
	soap_serializeheader(soap);
	soap_serialize___ns1__RTCreateOrder(soap, &soap_tmp___ns1__RTCreateOrder);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RTCreateOrder(soap, &soap_tmp___ns1__RTCreateOrder, "-ns1:RTCreateOrder", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RTCreateOrder(soap, &soap_tmp___ns1__RTCreateOrder, "-ns1:RTCreateOrder", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__RTCreateOrderResponse)
		return soap_closesock(soap);
	ns1__RTCreateOrderResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__RTCreateOrderResponse->soap_get(soap, "ns1:RTCreateOrderResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetOrderInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetOrderInfo *ns1__GetOrderInfo, _ns1__GetOrderInfoResponse *ns1__GetOrderInfoResponse)
{	struct __ns1__GetOrderInfo soap_tmp___ns1__GetOrderInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetOrderInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetOrderInfo.ns1__GetOrderInfo = ns1__GetOrderInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetOrderInfo(soap, &soap_tmp___ns1__GetOrderInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetOrderInfo(soap, &soap_tmp___ns1__GetOrderInfo, "-ns1:GetOrderInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetOrderInfo(soap, &soap_tmp___ns1__GetOrderInfo, "-ns1:GetOrderInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetOrderInfoResponse)
		return soap_closesock(soap);
	ns1__GetOrderInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetOrderInfoResponse->soap_get(soap, "ns1:GetOrderInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetInvalidationProviders(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetInvalidationProviders *ns1__GetInvalidationProviders, _ns1__GetInvalidationProvidersResponse *ns1__GetInvalidationProvidersResponse)
{	struct __ns1__GetInvalidationProviders soap_tmp___ns1__GetInvalidationProviders;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetInvalidationProviders";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetInvalidationProviders.ns1__GetInvalidationProviders = ns1__GetInvalidationProviders;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetInvalidationProviders(soap, &soap_tmp___ns1__GetInvalidationProviders);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetInvalidationProviders(soap, &soap_tmp___ns1__GetInvalidationProviders, "-ns1:GetInvalidationProviders", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetInvalidationProviders(soap, &soap_tmp___ns1__GetInvalidationProviders, "-ns1:GetInvalidationProviders", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetInvalidationProvidersResponse)
		return soap_closesock(soap);
	ns1__GetInvalidationProvidersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetInvalidationProvidersResponse->soap_get(soap, "ns1:GetInvalidationProvidersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RefundOrder(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__RefundOrder *ns1__RefundOrder, _ns1__RefundOrderResponse *ns1__RefundOrderResponse)
{	struct __ns1__RefundOrder soap_tmp___ns1__RefundOrder;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/RefundOrder";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RefundOrder.ns1__RefundOrder = ns1__RefundOrder;
	soap_serializeheader(soap);
	soap_serialize___ns1__RefundOrder(soap, &soap_tmp___ns1__RefundOrder);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RefundOrder(soap, &soap_tmp___ns1__RefundOrder, "-ns1:RefundOrder", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RefundOrder(soap, &soap_tmp___ns1__RefundOrder, "-ns1:RefundOrder", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__RefundOrderResponse)
		return soap_closesock(soap);
	ns1__RefundOrderResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__RefundOrderResponse->soap_get(soap, "ns1:RefundOrderResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetChangeFlightDate(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetChangeFlightDate *ns1__GetChangeFlightDate, _ns1__GetChangeFlightDateResponse *ns1__GetChangeFlightDateResponse)
{	struct __ns1__GetChangeFlightDate soap_tmp___ns1__GetChangeFlightDate;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ite3.baitour.com/comanage/baitourService.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.baitour.com/GetChangeFlightDate";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetChangeFlightDate.ns1__GetChangeFlightDate = ns1__GetChangeFlightDate;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetChangeFlightDate(soap, &soap_tmp___ns1__GetChangeFlightDate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetChangeFlightDate(soap, &soap_tmp___ns1__GetChangeFlightDate, "-ns1:GetChangeFlightDate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetChangeFlightDate(soap, &soap_tmp___ns1__GetChangeFlightDate, "-ns1:GetChangeFlightDate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetChangeFlightDateResponse)
		return soap_closesock(soap);
	ns1__GetChangeFlightDateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetChangeFlightDateResponse->soap_get(soap, "ns1:GetChangeFlightDateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
