/* soapServer.cpp
   Generated by gSOAP 2.8.16 from baitour.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.16 2013-11-17 16:35:12 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetAllCommonPolicy"))
		return soap_serve___ns1__GetAllCommonPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetAllCommonPolicyZIP"))
		return soap_serve___ns1__GetAllCommonPolicyZIP(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetAlterCommonPolicy"))
		return soap_serve___ns1__GetAlterCommonPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:MatchCommonPolicy"))
		return soap_serve___ns1__MatchCommonPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetAVPolicy"))
		return soap_serve___ns1__GetAVPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetDomesticMatchNormalZRateByID"))
		return soap_serve___ns1__GetDomesticMatchNormalZRateByID(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:DetailCreateOrder"))
		return soap_serve___ns1__DetailCreateOrder(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RTCreateOrder"))
		return soap_serve___ns1__RTCreateOrder(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetOrderInfo"))
		return soap_serve___ns1__GetOrderInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetInvalidationProviders"))
		return soap_serve___ns1__GetInvalidationProviders(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RefundOrder"))
		return soap_serve___ns1__RefundOrder(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetChangeFlightDate"))
		return soap_serve___ns1__GetChangeFlightDate(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetAllCommonPolicy(struct soap *soap)
{	struct __ns1__GetAllCommonPolicy soap_tmp___ns1__GetAllCommonPolicy;
	_ns1__GetAllCommonPolicyResponse ns1__GetAllCommonPolicyResponse;
	ns1__GetAllCommonPolicyResponse.soap_default(soap);
	soap_default___ns1__GetAllCommonPolicy(soap, &soap_tmp___ns1__GetAllCommonPolicy);
	if (!soap_get___ns1__GetAllCommonPolicy(soap, &soap_tmp___ns1__GetAllCommonPolicy, "-ns1:GetAllCommonPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetAllCommonPolicy(soap, soap_tmp___ns1__GetAllCommonPolicy.ns1__GetAllCommonPolicy, &ns1__GetAllCommonPolicyResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAllCommonPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAllCommonPolicyResponse.soap_put(soap, "ns1:GetAllCommonPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAllCommonPolicyResponse.soap_put(soap, "ns1:GetAllCommonPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetAllCommonPolicyZIP(struct soap *soap)
{	struct __ns1__GetAllCommonPolicyZIP soap_tmp___ns1__GetAllCommonPolicyZIP;
	_ns1__GetAllCommonPolicyZIPResponse ns1__GetAllCommonPolicyZIPResponse;
	ns1__GetAllCommonPolicyZIPResponse.soap_default(soap);
	soap_default___ns1__GetAllCommonPolicyZIP(soap, &soap_tmp___ns1__GetAllCommonPolicyZIP);
	if (!soap_get___ns1__GetAllCommonPolicyZIP(soap, &soap_tmp___ns1__GetAllCommonPolicyZIP, "-ns1:GetAllCommonPolicyZIP", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetAllCommonPolicyZIP(soap, soap_tmp___ns1__GetAllCommonPolicyZIP.ns1__GetAllCommonPolicyZIP, &ns1__GetAllCommonPolicyZIPResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAllCommonPolicyZIPResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAllCommonPolicyZIPResponse.soap_put(soap, "ns1:GetAllCommonPolicyZIPResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAllCommonPolicyZIPResponse.soap_put(soap, "ns1:GetAllCommonPolicyZIPResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetAlterCommonPolicy(struct soap *soap)
{	struct __ns1__GetAlterCommonPolicy soap_tmp___ns1__GetAlterCommonPolicy;
	_ns1__GetAlterCommonPolicyResponse ns1__GetAlterCommonPolicyResponse;
	ns1__GetAlterCommonPolicyResponse.soap_default(soap);
	soap_default___ns1__GetAlterCommonPolicy(soap, &soap_tmp___ns1__GetAlterCommonPolicy);
	if (!soap_get___ns1__GetAlterCommonPolicy(soap, &soap_tmp___ns1__GetAlterCommonPolicy, "-ns1:GetAlterCommonPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetAlterCommonPolicy(soap, soap_tmp___ns1__GetAlterCommonPolicy.ns1__GetAlterCommonPolicy, &ns1__GetAlterCommonPolicyResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAlterCommonPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAlterCommonPolicyResponse.soap_put(soap, "ns1:GetAlterCommonPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAlterCommonPolicyResponse.soap_put(soap, "ns1:GetAlterCommonPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__MatchCommonPolicy(struct soap *soap)
{	struct __ns1__MatchCommonPolicy soap_tmp___ns1__MatchCommonPolicy;
	_ns1__MatchCommonPolicyResponse ns1__MatchCommonPolicyResponse;
	ns1__MatchCommonPolicyResponse.soap_default(soap);
	soap_default___ns1__MatchCommonPolicy(soap, &soap_tmp___ns1__MatchCommonPolicy);
	if (!soap_get___ns1__MatchCommonPolicy(soap, &soap_tmp___ns1__MatchCommonPolicy, "-ns1:MatchCommonPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__MatchCommonPolicy(soap, soap_tmp___ns1__MatchCommonPolicy.ns1__MatchCommonPolicy, &ns1__MatchCommonPolicyResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__MatchCommonPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__MatchCommonPolicyResponse.soap_put(soap, "ns1:MatchCommonPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__MatchCommonPolicyResponse.soap_put(soap, "ns1:MatchCommonPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetAVPolicy(struct soap *soap)
{	struct __ns1__GetAVPolicy soap_tmp___ns1__GetAVPolicy;
	_ns1__GetAVPolicyResponse ns1__GetAVPolicyResponse;
	ns1__GetAVPolicyResponse.soap_default(soap);
	soap_default___ns1__GetAVPolicy(soap, &soap_tmp___ns1__GetAVPolicy);
	if (!soap_get___ns1__GetAVPolicy(soap, &soap_tmp___ns1__GetAVPolicy, "-ns1:GetAVPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetAVPolicy(soap, soap_tmp___ns1__GetAVPolicy.ns1__GetAVPolicy, &ns1__GetAVPolicyResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetAVPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetAVPolicyResponse.soap_put(soap, "ns1:GetAVPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetAVPolicyResponse.soap_put(soap, "ns1:GetAVPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetDomesticMatchNormalZRateByID(struct soap *soap)
{	struct __ns1__GetDomesticMatchNormalZRateByID soap_tmp___ns1__GetDomesticMatchNormalZRateByID;
	_ns1__GetDomesticMatchNormalZRateByIDResponse ns1__GetDomesticMatchNormalZRateByIDResponse;
	ns1__GetDomesticMatchNormalZRateByIDResponse.soap_default(soap);
	soap_default___ns1__GetDomesticMatchNormalZRateByID(soap, &soap_tmp___ns1__GetDomesticMatchNormalZRateByID);
	if (!soap_get___ns1__GetDomesticMatchNormalZRateByID(soap, &soap_tmp___ns1__GetDomesticMatchNormalZRateByID, "-ns1:GetDomesticMatchNormalZRateByID", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetDomesticMatchNormalZRateByID(soap, soap_tmp___ns1__GetDomesticMatchNormalZRateByID.ns1__GetDomesticMatchNormalZRateByID, &ns1__GetDomesticMatchNormalZRateByIDResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetDomesticMatchNormalZRateByIDResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetDomesticMatchNormalZRateByIDResponse.soap_put(soap, "ns1:GetDomesticMatchNormalZRateByIDResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetDomesticMatchNormalZRateByIDResponse.soap_put(soap, "ns1:GetDomesticMatchNormalZRateByIDResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__DetailCreateOrder(struct soap *soap)
{	struct __ns1__DetailCreateOrder soap_tmp___ns1__DetailCreateOrder;
	_ns1__DetailCreateOrderResponse ns1__DetailCreateOrderResponse;
	ns1__DetailCreateOrderResponse.soap_default(soap);
	soap_default___ns1__DetailCreateOrder(soap, &soap_tmp___ns1__DetailCreateOrder);
	if (!soap_get___ns1__DetailCreateOrder(soap, &soap_tmp___ns1__DetailCreateOrder, "-ns1:DetailCreateOrder", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__DetailCreateOrder(soap, soap_tmp___ns1__DetailCreateOrder.ns1__DetailCreateOrder, &ns1__DetailCreateOrderResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__DetailCreateOrderResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__DetailCreateOrderResponse.soap_put(soap, "ns1:DetailCreateOrderResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__DetailCreateOrderResponse.soap_put(soap, "ns1:DetailCreateOrderResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__RTCreateOrder(struct soap *soap)
{	struct __ns1__RTCreateOrder soap_tmp___ns1__RTCreateOrder;
	_ns1__RTCreateOrderResponse ns1__RTCreateOrderResponse;
	ns1__RTCreateOrderResponse.soap_default(soap);
	soap_default___ns1__RTCreateOrder(soap, &soap_tmp___ns1__RTCreateOrder);
	if (!soap_get___ns1__RTCreateOrder(soap, &soap_tmp___ns1__RTCreateOrder, "-ns1:RTCreateOrder", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__RTCreateOrder(soap, soap_tmp___ns1__RTCreateOrder.ns1__RTCreateOrder, &ns1__RTCreateOrderResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__RTCreateOrderResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__RTCreateOrderResponse.soap_put(soap, "ns1:RTCreateOrderResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__RTCreateOrderResponse.soap_put(soap, "ns1:RTCreateOrderResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetOrderInfo(struct soap *soap)
{	struct __ns1__GetOrderInfo soap_tmp___ns1__GetOrderInfo;
	_ns1__GetOrderInfoResponse ns1__GetOrderInfoResponse;
	ns1__GetOrderInfoResponse.soap_default(soap);
	soap_default___ns1__GetOrderInfo(soap, &soap_tmp___ns1__GetOrderInfo);
	if (!soap_get___ns1__GetOrderInfo(soap, &soap_tmp___ns1__GetOrderInfo, "-ns1:GetOrderInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetOrderInfo(soap, soap_tmp___ns1__GetOrderInfo.ns1__GetOrderInfo, &ns1__GetOrderInfoResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetOrderInfoResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetOrderInfoResponse.soap_put(soap, "ns1:GetOrderInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetOrderInfoResponse.soap_put(soap, "ns1:GetOrderInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetInvalidationProviders(struct soap *soap)
{	struct __ns1__GetInvalidationProviders soap_tmp___ns1__GetInvalidationProviders;
	_ns1__GetInvalidationProvidersResponse ns1__GetInvalidationProvidersResponse;
	ns1__GetInvalidationProvidersResponse.soap_default(soap);
	soap_default___ns1__GetInvalidationProviders(soap, &soap_tmp___ns1__GetInvalidationProviders);
	if (!soap_get___ns1__GetInvalidationProviders(soap, &soap_tmp___ns1__GetInvalidationProviders, "-ns1:GetInvalidationProviders", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetInvalidationProviders(soap, soap_tmp___ns1__GetInvalidationProviders.ns1__GetInvalidationProviders, &ns1__GetInvalidationProvidersResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetInvalidationProvidersResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetInvalidationProvidersResponse.soap_put(soap, "ns1:GetInvalidationProvidersResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetInvalidationProvidersResponse.soap_put(soap, "ns1:GetInvalidationProvidersResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__RefundOrder(struct soap *soap)
{	struct __ns1__RefundOrder soap_tmp___ns1__RefundOrder;
	_ns1__RefundOrderResponse ns1__RefundOrderResponse;
	ns1__RefundOrderResponse.soap_default(soap);
	soap_default___ns1__RefundOrder(soap, &soap_tmp___ns1__RefundOrder);
	if (!soap_get___ns1__RefundOrder(soap, &soap_tmp___ns1__RefundOrder, "-ns1:RefundOrder", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__RefundOrder(soap, soap_tmp___ns1__RefundOrder.ns1__RefundOrder, &ns1__RefundOrderResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__RefundOrderResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__RefundOrderResponse.soap_put(soap, "ns1:RefundOrderResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__RefundOrderResponse.soap_put(soap, "ns1:RefundOrderResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetChangeFlightDate(struct soap *soap)
{	struct __ns1__GetChangeFlightDate soap_tmp___ns1__GetChangeFlightDate;
	_ns1__GetChangeFlightDateResponse ns1__GetChangeFlightDateResponse;
	ns1__GetChangeFlightDateResponse.soap_default(soap);
	soap_default___ns1__GetChangeFlightDate(soap, &soap_tmp___ns1__GetChangeFlightDate);
	if (!soap_get___ns1__GetChangeFlightDate(soap, &soap_tmp___ns1__GetChangeFlightDate, "-ns1:GetChangeFlightDate", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetChangeFlightDate(soap, soap_tmp___ns1__GetChangeFlightDate.ns1__GetChangeFlightDate, &ns1__GetChangeFlightDateResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns1__GetChangeFlightDateResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetChangeFlightDateResponse.soap_put(soap, "ns1:GetChangeFlightDateResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetChangeFlightDateResponse.soap_put(soap, "ns1:GetChangeFlightDateResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
