/* soapBasicHttpBinding_USCOREixinghaiProxy.cpp
   Generated by gSOAP 2.8.17r from temp.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapBasicHttpBinding_USCOREixinghaiProxy.h"

BasicHttpBinding_USCOREixinghaiProxy::BasicHttpBinding_USCOREixinghaiProxy()
{	this->soap = soap_new();
	this->own = true;
	BasicHttpBinding_USCOREixinghaiProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

BasicHttpBinding_USCOREixinghaiProxy::BasicHttpBinding_USCOREixinghaiProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	BasicHttpBinding_USCOREixinghaiProxy_init(_soap->imode, _soap->omode);
}

BasicHttpBinding_USCOREixinghaiProxy::BasicHttpBinding_USCOREixinghaiProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	BasicHttpBinding_USCOREixinghaiProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

BasicHttpBinding_USCOREixinghaiProxy::BasicHttpBinding_USCOREixinghaiProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	BasicHttpBinding_USCOREixinghaiProxy_init(iomode, iomode);
}

BasicHttpBinding_USCOREixinghaiProxy::BasicHttpBinding_USCOREixinghaiProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	BasicHttpBinding_USCOREixinghaiProxy_init(iomode, iomode);
	soap_endpoint = url;
}

BasicHttpBinding_USCOREixinghaiProxy::BasicHttpBinding_USCOREixinghaiProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	BasicHttpBinding_USCOREixinghaiProxy_init(imode, omode);
}

BasicHttpBinding_USCOREixinghaiProxy::~BasicHttpBinding_USCOREixinghaiProxy()
{	if (this->own)
		soap_free(this->soap);
}

void BasicHttpBinding_USCOREixinghaiProxy::BasicHttpBinding_USCOREixinghaiProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"tempuri", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void BasicHttpBinding_USCOREixinghaiProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void BasicHttpBinding_USCOREixinghaiProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	BasicHttpBinding_USCOREixinghaiProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void BasicHttpBinding_USCOREixinghaiProxy::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *BasicHttpBinding_USCOREixinghaiProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *BasicHttpBinding_USCOREixinghaiProxy::soap_fault()
{	return this->soap->fault;
}

const char *BasicHttpBinding_USCOREixinghaiProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *BasicHttpBinding_USCOREixinghaiProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void BasicHttpBinding_USCOREixinghaiProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void BasicHttpBinding_USCOREixinghaiProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *BasicHttpBinding_USCOREixinghaiProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int BasicHttpBinding_USCOREixinghaiProxy::Get_USCOREHotel_USCOREList(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCOREList *tempuri__Get_USCOREHotel_USCOREList, _tempuri__Get_USCOREHotel_USCOREListResponse *tempuri__Get_USCOREHotel_USCOREListResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Get_USCOREHotel_USCOREList soap_tmp___tempuri__Get_USCOREHotel_USCOREList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Get_Hotel_List";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Get_USCOREHotel_USCOREList.tempuri__Get_USCOREHotel_USCOREList = tempuri__Get_USCOREHotel_USCOREList;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Get_USCOREHotel_USCOREList(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Get_USCOREHotel_USCOREList(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREList, "-tempuri:Get_Hotel_List", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Get_USCOREHotel_USCOREList(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREList, "-tempuri:Get_Hotel_List", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Get_USCOREHotel_USCOREListResponse)
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCOREListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCOREListResponse->soap_get(soap, "tempuri:Get_Hotel_ListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Get_USCOREHotel_USCOREInfo(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCOREInfo *tempuri__Get_USCOREHotel_USCOREInfo, _tempuri__Get_USCOREHotel_USCOREInfoResponse *tempuri__Get_USCOREHotel_USCOREInfoResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Get_USCOREHotel_USCOREInfo soap_tmp___tempuri__Get_USCOREHotel_USCOREInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Get_Hotel_Info";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Get_USCOREHotel_USCOREInfo.tempuri__Get_USCOREHotel_USCOREInfo = tempuri__Get_USCOREHotel_USCOREInfo;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Get_USCOREHotel_USCOREInfo(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Get_USCOREHotel_USCOREInfo(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREInfo, "-tempuri:Get_Hotel_Info", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Get_USCOREHotel_USCOREInfo(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREInfo, "-tempuri:Get_Hotel_Info", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Get_USCOREHotel_USCOREInfoResponse)
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCOREInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCOREInfoResponse->soap_get(soap, "tempuri:Get_Hotel_InfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Get_USCOREHotel_USCOREPrice(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCOREPrice *tempuri__Get_USCOREHotel_USCOREPrice, _tempuri__Get_USCOREHotel_USCOREPriceResponse *tempuri__Get_USCOREHotel_USCOREPriceResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Get_USCOREHotel_USCOREPrice soap_tmp___tempuri__Get_USCOREHotel_USCOREPrice;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Get_Hotel_Price";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Get_USCOREHotel_USCOREPrice.tempuri__Get_USCOREHotel_USCOREPrice = tempuri__Get_USCOREHotel_USCOREPrice;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Get_USCOREHotel_USCOREPrice(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREPrice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Get_USCOREHotel_USCOREPrice(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREPrice, "-tempuri:Get_Hotel_Price", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Get_USCOREHotel_USCOREPrice(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCOREPrice, "-tempuri:Get_Hotel_Price", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Get_USCOREHotel_USCOREPriceResponse)
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCOREPriceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCOREPriceResponse->soap_get(soap, "tempuri:Get_Hotel_PriceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Get_USCOREHotel_USCORERoomState(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCORERoomState *tempuri__Get_USCOREHotel_USCORERoomState, _tempuri__Get_USCOREHotel_USCORERoomStateResponse *tempuri__Get_USCOREHotel_USCORERoomStateResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Get_USCOREHotel_USCORERoomState soap_tmp___tempuri__Get_USCOREHotel_USCORERoomState;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Get_Hotel_RoomState";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Get_USCOREHotel_USCORERoomState.tempuri__Get_USCOREHotel_USCORERoomState = tempuri__Get_USCOREHotel_USCORERoomState;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Get_USCOREHotel_USCORERoomState(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCORERoomState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Get_USCOREHotel_USCORERoomState(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCORERoomState, "-tempuri:Get_Hotel_RoomState", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Get_USCOREHotel_USCORERoomState(soap, &soap_tmp___tempuri__Get_USCOREHotel_USCORERoomState, "-tempuri:Get_Hotel_RoomState", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Get_USCOREHotel_USCORERoomStateResponse)
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCORERoomStateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Get_USCOREHotel_USCORERoomStateResponse->soap_get(soap, "tempuri:Get_Hotel_RoomStateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Book_USCOREAdd(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREAdd *tempuri__Book_USCOREAdd, _tempuri__Book_USCOREAddResponse *tempuri__Book_USCOREAddResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Book_USCOREAdd soap_tmp___tempuri__Book_USCOREAdd;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Book_Add";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Book_USCOREAdd.tempuri__Book_USCOREAdd = tempuri__Book_USCOREAdd;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Book_USCOREAdd(soap, &soap_tmp___tempuri__Book_USCOREAdd);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Book_USCOREAdd(soap, &soap_tmp___tempuri__Book_USCOREAdd, "-tempuri:Book_Add", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Book_USCOREAdd(soap, &soap_tmp___tempuri__Book_USCOREAdd, "-tempuri:Book_Add", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Book_USCOREAddResponse)
		return soap_closesock(soap);
	tempuri__Book_USCOREAddResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Book_USCOREAddResponse->soap_get(soap, "tempuri:Book_AddResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Book_USCOREModify_USCOREHotel(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREModify_USCOREHotel *tempuri__Book_USCOREModify_USCOREHotel, _tempuri__Book_USCOREModify_USCOREHotelResponse *tempuri__Book_USCOREModify_USCOREHotelResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Book_USCOREModify_USCOREHotel soap_tmp___tempuri__Book_USCOREModify_USCOREHotel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Book_Modify_Hotel";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Book_USCOREModify_USCOREHotel.tempuri__Book_USCOREModify_USCOREHotel = tempuri__Book_USCOREModify_USCOREHotel;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Book_USCOREModify_USCOREHotel(soap, &soap_tmp___tempuri__Book_USCOREModify_USCOREHotel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Book_USCOREModify_USCOREHotel(soap, &soap_tmp___tempuri__Book_USCOREModify_USCOREHotel, "-tempuri:Book_Modify_Hotel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Book_USCOREModify_USCOREHotel(soap, &soap_tmp___tempuri__Book_USCOREModify_USCOREHotel, "-tempuri:Book_Modify_Hotel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Book_USCOREModify_USCOREHotelResponse)
		return soap_closesock(soap);
	tempuri__Book_USCOREModify_USCOREHotelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Book_USCOREModify_USCOREHotelResponse->soap_get(soap, "tempuri:Book_Modify_HotelResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Book_USCOREModify_USCOREPlus(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREModify_USCOREPlus *tempuri__Book_USCOREModify_USCOREPlus, _tempuri__Book_USCOREModify_USCOREPlusResponse *tempuri__Book_USCOREModify_USCOREPlusResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Book_USCOREModify_USCOREPlus soap_tmp___tempuri__Book_USCOREModify_USCOREPlus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Book_Modify_Plus";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Book_USCOREModify_USCOREPlus.tempuri__Book_USCOREModify_USCOREPlus = tempuri__Book_USCOREModify_USCOREPlus;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Book_USCOREModify_USCOREPlus(soap, &soap_tmp___tempuri__Book_USCOREModify_USCOREPlus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Book_USCOREModify_USCOREPlus(soap, &soap_tmp___tempuri__Book_USCOREModify_USCOREPlus, "-tempuri:Book_Modify_Plus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Book_USCOREModify_USCOREPlus(soap, &soap_tmp___tempuri__Book_USCOREModify_USCOREPlus, "-tempuri:Book_Modify_Plus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Book_USCOREModify_USCOREPlusResponse)
		return soap_closesock(soap);
	tempuri__Book_USCOREModify_USCOREPlusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Book_USCOREModify_USCOREPlusResponse->soap_get(soap, "tempuri:Book_Modify_PlusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Book_USCOREApply(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREApply *tempuri__Book_USCOREApply, _tempuri__Book_USCOREApplyResponse *tempuri__Book_USCOREApplyResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Book_USCOREApply soap_tmp___tempuri__Book_USCOREApply;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Book_Apply";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Book_USCOREApply.tempuri__Book_USCOREApply = tempuri__Book_USCOREApply;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Book_USCOREApply(soap, &soap_tmp___tempuri__Book_USCOREApply);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Book_USCOREApply(soap, &soap_tmp___tempuri__Book_USCOREApply, "-tempuri:Book_Apply", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Book_USCOREApply(soap, &soap_tmp___tempuri__Book_USCOREApply, "-tempuri:Book_Apply", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Book_USCOREApplyResponse)
		return soap_closesock(soap);
	tempuri__Book_USCOREApplyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Book_USCOREApplyResponse->soap_get(soap, "tempuri:Book_ApplyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Get_USCOREOrder(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREOrder *tempuri__Get_USCOREOrder, _tempuri__Get_USCOREOrderResponse *tempuri__Get_USCOREOrderResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Get_USCOREOrder soap_tmp___tempuri__Get_USCOREOrder;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Get_Order";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Get_USCOREOrder.tempuri__Get_USCOREOrder = tempuri__Get_USCOREOrder;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Get_USCOREOrder(soap, &soap_tmp___tempuri__Get_USCOREOrder);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Get_USCOREOrder(soap, &soap_tmp___tempuri__Get_USCOREOrder, "-tempuri:Get_Order", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Get_USCOREOrder(soap, &soap_tmp___tempuri__Get_USCOREOrder, "-tempuri:Get_Order", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Get_USCOREOrderResponse)
		return soap_closesock(soap);
	tempuri__Get_USCOREOrderResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Get_USCOREOrderResponse->soap_get(soap, "tempuri:Get_OrderResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREixinghaiProxy::Get_USCOREOrder_USCOREList(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREOrder_USCOREList *tempuri__Get_USCOREOrder_USCOREList, _tempuri__Get_USCOREOrder_USCOREListResponse *tempuri__Get_USCOREOrder_USCOREListResponse)
{	struct soap *soap = this->soap;
	struct __tempuri__Get_USCOREOrder_USCOREList soap_tmp___tempuri__Get_USCOREOrder_USCOREList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservice.xinghaitour.com/WebService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ixinghai/Get_Order_List";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__Get_USCOREOrder_USCOREList.tempuri__Get_USCOREOrder_USCOREList = tempuri__Get_USCOREOrder_USCOREList;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___tempuri__Get_USCOREOrder_USCOREList(soap, &soap_tmp___tempuri__Get_USCOREOrder_USCOREList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Get_USCOREOrder_USCOREList(soap, &soap_tmp___tempuri__Get_USCOREOrder_USCOREList, "-tempuri:Get_Order_List", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Get_USCOREOrder_USCOREList(soap, &soap_tmp___tempuri__Get_USCOREOrder_USCOREList, "-tempuri:Get_Order_List", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__Get_USCOREOrder_USCOREListResponse)
		return soap_closesock(soap);
	tempuri__Get_USCOREOrder_USCOREListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__Get_USCOREOrder_USCOREListResponse->soap_get(soap, "tempuri:Get_Order_ListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
