/* soapBasicHttpBinding_USCOREixinghaiProxy.h
   Generated by gSOAP 2.8.17r from temp.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBasicHttpBinding_USCOREixinghaiProxy_H
#define soapBasicHttpBinding_USCOREixinghaiProxy_H
#include "soapH.h"

class SOAP_CMAC BasicHttpBinding_USCOREixinghaiProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREixinghaiProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BasicHttpBinding_USCOREixinghaiProxy();
	/// Constructor to use/share an engine state
	BasicHttpBinding_USCOREixinghaiProxy(struct soap*);
	/// Constructor with endpoint URL
	BasicHttpBinding_USCOREixinghaiProxy(const char *url);
	/// Constructor with engine input+output mode control
	BasicHttpBinding_USCOREixinghaiProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	BasicHttpBinding_USCOREixinghaiProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	BasicHttpBinding_USCOREixinghaiProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BasicHttpBinding_USCOREixinghaiProxy();
	/// Initializer used by constructors
	virtual	void BasicHttpBinding_USCOREixinghaiProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'Get_Hotel_List' (returns error code or SOAP_OK)
	virtual	int Get_USCOREHotel_USCOREList(_tempuri__Get_USCOREHotel_USCOREList *tempuri__Get_USCOREHotel_USCOREList, _tempuri__Get_USCOREHotel_USCOREListResponse *tempuri__Get_USCOREHotel_USCOREListResponse) { return this->Get_USCOREHotel_USCOREList(NULL, NULL, tempuri__Get_USCOREHotel_USCOREList, tempuri__Get_USCOREHotel_USCOREListResponse); }
	virtual	int Get_USCOREHotel_USCOREList(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCOREList *tempuri__Get_USCOREHotel_USCOREList, _tempuri__Get_USCOREHotel_USCOREListResponse *tempuri__Get_USCOREHotel_USCOREListResponse);

	/// Web service operation 'Get_Hotel_Info' (returns error code or SOAP_OK)
	virtual	int Get_USCOREHotel_USCOREInfo(_tempuri__Get_USCOREHotel_USCOREInfo *tempuri__Get_USCOREHotel_USCOREInfo, _tempuri__Get_USCOREHotel_USCOREInfoResponse *tempuri__Get_USCOREHotel_USCOREInfoResponse) { return this->Get_USCOREHotel_USCOREInfo(NULL, NULL, tempuri__Get_USCOREHotel_USCOREInfo, tempuri__Get_USCOREHotel_USCOREInfoResponse); }
	virtual	int Get_USCOREHotel_USCOREInfo(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCOREInfo *tempuri__Get_USCOREHotel_USCOREInfo, _tempuri__Get_USCOREHotel_USCOREInfoResponse *tempuri__Get_USCOREHotel_USCOREInfoResponse);

	/// Web service operation 'Get_Hotel_Price' (returns error code or SOAP_OK)
	virtual	int Get_USCOREHotel_USCOREPrice(_tempuri__Get_USCOREHotel_USCOREPrice *tempuri__Get_USCOREHotel_USCOREPrice, _tempuri__Get_USCOREHotel_USCOREPriceResponse *tempuri__Get_USCOREHotel_USCOREPriceResponse) { return this->Get_USCOREHotel_USCOREPrice(NULL, NULL, tempuri__Get_USCOREHotel_USCOREPrice, tempuri__Get_USCOREHotel_USCOREPriceResponse); }
	virtual	int Get_USCOREHotel_USCOREPrice(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCOREPrice *tempuri__Get_USCOREHotel_USCOREPrice, _tempuri__Get_USCOREHotel_USCOREPriceResponse *tempuri__Get_USCOREHotel_USCOREPriceResponse);

	/// Web service operation 'Get_Hotel_RoomState' (returns error code or SOAP_OK)
	virtual	int Get_USCOREHotel_USCORERoomState(_tempuri__Get_USCOREHotel_USCORERoomState *tempuri__Get_USCOREHotel_USCORERoomState, _tempuri__Get_USCOREHotel_USCORERoomStateResponse *tempuri__Get_USCOREHotel_USCORERoomStateResponse) { return this->Get_USCOREHotel_USCORERoomState(NULL, NULL, tempuri__Get_USCOREHotel_USCORERoomState, tempuri__Get_USCOREHotel_USCORERoomStateResponse); }
	virtual	int Get_USCOREHotel_USCORERoomState(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREHotel_USCORERoomState *tempuri__Get_USCOREHotel_USCORERoomState, _tempuri__Get_USCOREHotel_USCORERoomStateResponse *tempuri__Get_USCOREHotel_USCORERoomStateResponse);

	/// Web service operation 'Book_Add' (returns error code or SOAP_OK)
	virtual	int Book_USCOREAdd(_tempuri__Book_USCOREAdd *tempuri__Book_USCOREAdd, _tempuri__Book_USCOREAddResponse *tempuri__Book_USCOREAddResponse) { return this->Book_USCOREAdd(NULL, NULL, tempuri__Book_USCOREAdd, tempuri__Book_USCOREAddResponse); }
	virtual	int Book_USCOREAdd(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREAdd *tempuri__Book_USCOREAdd, _tempuri__Book_USCOREAddResponse *tempuri__Book_USCOREAddResponse);

	/// Web service operation 'Book_Modify_Hotel' (returns error code or SOAP_OK)
	virtual	int Book_USCOREModify_USCOREHotel(_tempuri__Book_USCOREModify_USCOREHotel *tempuri__Book_USCOREModify_USCOREHotel, _tempuri__Book_USCOREModify_USCOREHotelResponse *tempuri__Book_USCOREModify_USCOREHotelResponse) { return this->Book_USCOREModify_USCOREHotel(NULL, NULL, tempuri__Book_USCOREModify_USCOREHotel, tempuri__Book_USCOREModify_USCOREHotelResponse); }
	virtual	int Book_USCOREModify_USCOREHotel(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREModify_USCOREHotel *tempuri__Book_USCOREModify_USCOREHotel, _tempuri__Book_USCOREModify_USCOREHotelResponse *tempuri__Book_USCOREModify_USCOREHotelResponse);

	/// Web service operation 'Book_Modify_Plus' (returns error code or SOAP_OK)
	virtual	int Book_USCOREModify_USCOREPlus(_tempuri__Book_USCOREModify_USCOREPlus *tempuri__Book_USCOREModify_USCOREPlus, _tempuri__Book_USCOREModify_USCOREPlusResponse *tempuri__Book_USCOREModify_USCOREPlusResponse) { return this->Book_USCOREModify_USCOREPlus(NULL, NULL, tempuri__Book_USCOREModify_USCOREPlus, tempuri__Book_USCOREModify_USCOREPlusResponse); }
	virtual	int Book_USCOREModify_USCOREPlus(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREModify_USCOREPlus *tempuri__Book_USCOREModify_USCOREPlus, _tempuri__Book_USCOREModify_USCOREPlusResponse *tempuri__Book_USCOREModify_USCOREPlusResponse);

	/// Web service operation 'Book_Apply' (returns error code or SOAP_OK)
	virtual	int Book_USCOREApply(_tempuri__Book_USCOREApply *tempuri__Book_USCOREApply, _tempuri__Book_USCOREApplyResponse *tempuri__Book_USCOREApplyResponse) { return this->Book_USCOREApply(NULL, NULL, tempuri__Book_USCOREApply, tempuri__Book_USCOREApplyResponse); }
	virtual	int Book_USCOREApply(const char *endpoint, const char *soap_action, _tempuri__Book_USCOREApply *tempuri__Book_USCOREApply, _tempuri__Book_USCOREApplyResponse *tempuri__Book_USCOREApplyResponse);

	/// Web service operation 'Get_Order' (returns error code or SOAP_OK)
	virtual	int Get_USCOREOrder(_tempuri__Get_USCOREOrder *tempuri__Get_USCOREOrder, _tempuri__Get_USCOREOrderResponse *tempuri__Get_USCOREOrderResponse) { return this->Get_USCOREOrder(NULL, NULL, tempuri__Get_USCOREOrder, tempuri__Get_USCOREOrderResponse); }
	virtual	int Get_USCOREOrder(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREOrder *tempuri__Get_USCOREOrder, _tempuri__Get_USCOREOrderResponse *tempuri__Get_USCOREOrderResponse);

	/// Web service operation 'Get_Order_List' (returns error code or SOAP_OK)
	virtual	int Get_USCOREOrder_USCOREList(_tempuri__Get_USCOREOrder_USCOREList *tempuri__Get_USCOREOrder_USCOREList, _tempuri__Get_USCOREOrder_USCOREListResponse *tempuri__Get_USCOREOrder_USCOREListResponse) { return this->Get_USCOREOrder_USCOREList(NULL, NULL, tempuri__Get_USCOREOrder_USCOREList, tempuri__Get_USCOREOrder_USCOREListResponse); }
	virtual	int Get_USCOREOrder_USCOREList(const char *endpoint, const char *soap_action, _tempuri__Get_USCOREOrder_USCOREList *tempuri__Get_USCOREOrder_USCOREList, _tempuri__Get_USCOREOrder_USCOREListResponse *tempuri__Get_USCOREOrder_USCOREListResponse);
};
#endif
