/* soapBaitourServiceSoapProxy.h
   Generated by gSOAP 2.8.16 from temp.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBaitourServiceSoapProxy_H
#define soapBaitourServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC BaitourServiceSoapProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'BaitourServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BaitourServiceSoapProxy();
	/// Constructor to use/share an engine state
	BaitourServiceSoapProxy(struct soap*);
	/// Constructor with endpoint URL
	BaitourServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	BaitourServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	BaitourServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	BaitourServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BaitourServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void BaitourServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetAllCommonPolicy' (returns error code or SOAP_OK)
	virtual	int GetAllCommonPolicy(_ns1__GetAllCommonPolicy *ns1__GetAllCommonPolicy, _ns1__GetAllCommonPolicyResponse *ns1__GetAllCommonPolicyResponse) { return this->GetAllCommonPolicy(NULL, NULL, ns1__GetAllCommonPolicy, ns1__GetAllCommonPolicyResponse); }
	virtual	int GetAllCommonPolicy(const char *endpoint, const char *soap_action, _ns1__GetAllCommonPolicy *ns1__GetAllCommonPolicy, _ns1__GetAllCommonPolicyResponse *ns1__GetAllCommonPolicyResponse);

	/// Web service operation 'GetAllCommonPolicyZIP' (returns error code or SOAP_OK)
	virtual	int GetAllCommonPolicyZIP(_ns1__GetAllCommonPolicyZIP *ns1__GetAllCommonPolicyZIP, _ns1__GetAllCommonPolicyZIPResponse *ns1__GetAllCommonPolicyZIPResponse) { return this->GetAllCommonPolicyZIP(NULL, NULL, ns1__GetAllCommonPolicyZIP, ns1__GetAllCommonPolicyZIPResponse); }
	virtual	int GetAllCommonPolicyZIP(const char *endpoint, const char *soap_action, _ns1__GetAllCommonPolicyZIP *ns1__GetAllCommonPolicyZIP, _ns1__GetAllCommonPolicyZIPResponse *ns1__GetAllCommonPolicyZIPResponse);

	/// Web service operation 'GetAlterCommonPolicy' (returns error code or SOAP_OK)
	virtual	int GetAlterCommonPolicy(_ns1__GetAlterCommonPolicy *ns1__GetAlterCommonPolicy, _ns1__GetAlterCommonPolicyResponse *ns1__GetAlterCommonPolicyResponse) { return this->GetAlterCommonPolicy(NULL, NULL, ns1__GetAlterCommonPolicy, ns1__GetAlterCommonPolicyResponse); }
	virtual	int GetAlterCommonPolicy(const char *endpoint, const char *soap_action, _ns1__GetAlterCommonPolicy *ns1__GetAlterCommonPolicy, _ns1__GetAlterCommonPolicyResponse *ns1__GetAlterCommonPolicyResponse);

	/// Web service operation 'MatchCommonPolicy' (returns error code or SOAP_OK)
	virtual	int MatchCommonPolicy(_ns1__MatchCommonPolicy *ns1__MatchCommonPolicy, _ns1__MatchCommonPolicyResponse *ns1__MatchCommonPolicyResponse) { return this->MatchCommonPolicy(NULL, NULL, ns1__MatchCommonPolicy, ns1__MatchCommonPolicyResponse); }
	virtual	int MatchCommonPolicy(const char *endpoint, const char *soap_action, _ns1__MatchCommonPolicy *ns1__MatchCommonPolicy, _ns1__MatchCommonPolicyResponse *ns1__MatchCommonPolicyResponse);

	/// Web service operation 'GetAVPolicy' (returns error code or SOAP_OK)
	virtual	int GetAVPolicy(_ns1__GetAVPolicy *ns1__GetAVPolicy, _ns1__GetAVPolicyResponse *ns1__GetAVPolicyResponse) { return this->GetAVPolicy(NULL, NULL, ns1__GetAVPolicy, ns1__GetAVPolicyResponse); }
	virtual	int GetAVPolicy(const char *endpoint, const char *soap_action, _ns1__GetAVPolicy *ns1__GetAVPolicy, _ns1__GetAVPolicyResponse *ns1__GetAVPolicyResponse);

	/// Web service operation 'GetDomesticMatchNormalZRateByID' (returns error code or SOAP_OK)
	virtual	int GetDomesticMatchNormalZRateByID(_ns1__GetDomesticMatchNormalZRateByID *ns1__GetDomesticMatchNormalZRateByID, _ns1__GetDomesticMatchNormalZRateByIDResponse *ns1__GetDomesticMatchNormalZRateByIDResponse) { return this->GetDomesticMatchNormalZRateByID(NULL, NULL, ns1__GetDomesticMatchNormalZRateByID, ns1__GetDomesticMatchNormalZRateByIDResponse); }
	virtual	int GetDomesticMatchNormalZRateByID(const char *endpoint, const char *soap_action, _ns1__GetDomesticMatchNormalZRateByID *ns1__GetDomesticMatchNormalZRateByID, _ns1__GetDomesticMatchNormalZRateByIDResponse *ns1__GetDomesticMatchNormalZRateByIDResponse);

	/// Web service operation 'DetailCreateOrder' (returns error code or SOAP_OK)
	virtual	int DetailCreateOrder(_ns1__DetailCreateOrder *ns1__DetailCreateOrder, _ns1__DetailCreateOrderResponse *ns1__DetailCreateOrderResponse) { return this->DetailCreateOrder(NULL, NULL, ns1__DetailCreateOrder, ns1__DetailCreateOrderResponse); }
	virtual	int DetailCreateOrder(const char *endpoint, const char *soap_action, _ns1__DetailCreateOrder *ns1__DetailCreateOrder, _ns1__DetailCreateOrderResponse *ns1__DetailCreateOrderResponse);

	/// Web service operation 'RTCreateOrder' (returns error code or SOAP_OK)
	virtual	int RTCreateOrder(_ns1__RTCreateOrder *ns1__RTCreateOrder, _ns1__RTCreateOrderResponse *ns1__RTCreateOrderResponse) { return this->RTCreateOrder(NULL, NULL, ns1__RTCreateOrder, ns1__RTCreateOrderResponse); }
	virtual	int RTCreateOrder(const char *endpoint, const char *soap_action, _ns1__RTCreateOrder *ns1__RTCreateOrder, _ns1__RTCreateOrderResponse *ns1__RTCreateOrderResponse);

	/// Web service operation 'GetOrderInfo' (returns error code or SOAP_OK)
	virtual	int GetOrderInfo(_ns1__GetOrderInfo *ns1__GetOrderInfo, _ns1__GetOrderInfoResponse *ns1__GetOrderInfoResponse) { return this->GetOrderInfo(NULL, NULL, ns1__GetOrderInfo, ns1__GetOrderInfoResponse); }
	virtual	int GetOrderInfo(const char *endpoint, const char *soap_action, _ns1__GetOrderInfo *ns1__GetOrderInfo, _ns1__GetOrderInfoResponse *ns1__GetOrderInfoResponse);

	/// Web service operation 'GetInvalidationProviders' (returns error code or SOAP_OK)
	virtual	int GetInvalidationProviders(_ns1__GetInvalidationProviders *ns1__GetInvalidationProviders, _ns1__GetInvalidationProvidersResponse *ns1__GetInvalidationProvidersResponse) { return this->GetInvalidationProviders(NULL, NULL, ns1__GetInvalidationProviders, ns1__GetInvalidationProvidersResponse); }
	virtual	int GetInvalidationProviders(const char *endpoint, const char *soap_action, _ns1__GetInvalidationProviders *ns1__GetInvalidationProviders, _ns1__GetInvalidationProvidersResponse *ns1__GetInvalidationProvidersResponse);

	/// Web service operation 'RefundOrder' (returns error code or SOAP_OK)
	virtual	int RefundOrder(_ns1__RefundOrder *ns1__RefundOrder, _ns1__RefundOrderResponse *ns1__RefundOrderResponse) { return this->RefundOrder(NULL, NULL, ns1__RefundOrder, ns1__RefundOrderResponse); }
	virtual	int RefundOrder(const char *endpoint, const char *soap_action, _ns1__RefundOrder *ns1__RefundOrder, _ns1__RefundOrderResponse *ns1__RefundOrderResponse);

	/// Web service operation 'GetChangeFlightDate' (returns error code or SOAP_OK)
	virtual	int GetChangeFlightDate(_ns1__GetChangeFlightDate *ns1__GetChangeFlightDate, _ns1__GetChangeFlightDateResponse *ns1__GetChangeFlightDateResponse) { return this->GetChangeFlightDate(NULL, NULL, ns1__GetChangeFlightDate, ns1__GetChangeFlightDateResponse); }
	virtual	int GetChangeFlightDate(const char *endpoint, const char *soap_action, _ns1__GetChangeFlightDate *ns1__GetChangeFlightDate, _ns1__GetChangeFlightDateResponse *ns1__GetChangeFlightDateResponse);

	/// Web service operation 'GetAllCommonPolicy' (returns error code or SOAP_OK)
	virtual	int GetAllCommonPolicy_(_ns1__GetAllCommonPolicy *ns1__GetAllCommonPolicy, _ns1__GetAllCommonPolicyResponse *ns1__GetAllCommonPolicyResponse) { return this->GetAllCommonPolicy_(NULL, NULL, ns1__GetAllCommonPolicy, ns1__GetAllCommonPolicyResponse); }
	virtual	int GetAllCommonPolicy_(const char *endpoint, const char *soap_action, _ns1__GetAllCommonPolicy *ns1__GetAllCommonPolicy, _ns1__GetAllCommonPolicyResponse *ns1__GetAllCommonPolicyResponse);

	/// Web service operation 'GetAllCommonPolicyZIP' (returns error code or SOAP_OK)
	virtual	int GetAllCommonPolicyZIP_(_ns1__GetAllCommonPolicyZIP *ns1__GetAllCommonPolicyZIP, _ns1__GetAllCommonPolicyZIPResponse *ns1__GetAllCommonPolicyZIPResponse) { return this->GetAllCommonPolicyZIP_(NULL, NULL, ns1__GetAllCommonPolicyZIP, ns1__GetAllCommonPolicyZIPResponse); }
	virtual	int GetAllCommonPolicyZIP_(const char *endpoint, const char *soap_action, _ns1__GetAllCommonPolicyZIP *ns1__GetAllCommonPolicyZIP, _ns1__GetAllCommonPolicyZIPResponse *ns1__GetAllCommonPolicyZIPResponse);

	/// Web service operation 'GetAlterCommonPolicy' (returns error code or SOAP_OK)
	virtual	int GetAlterCommonPolicy_(_ns1__GetAlterCommonPolicy *ns1__GetAlterCommonPolicy, _ns1__GetAlterCommonPolicyResponse *ns1__GetAlterCommonPolicyResponse) { return this->GetAlterCommonPolicy_(NULL, NULL, ns1__GetAlterCommonPolicy, ns1__GetAlterCommonPolicyResponse); }
	virtual	int GetAlterCommonPolicy_(const char *endpoint, const char *soap_action, _ns1__GetAlterCommonPolicy *ns1__GetAlterCommonPolicy, _ns1__GetAlterCommonPolicyResponse *ns1__GetAlterCommonPolicyResponse);

	/// Web service operation 'MatchCommonPolicy' (returns error code or SOAP_OK)
	virtual	int MatchCommonPolicy_(_ns1__MatchCommonPolicy *ns1__MatchCommonPolicy, _ns1__MatchCommonPolicyResponse *ns1__MatchCommonPolicyResponse) { return this->MatchCommonPolicy_(NULL, NULL, ns1__MatchCommonPolicy, ns1__MatchCommonPolicyResponse); }
	virtual	int MatchCommonPolicy_(const char *endpoint, const char *soap_action, _ns1__MatchCommonPolicy *ns1__MatchCommonPolicy, _ns1__MatchCommonPolicyResponse *ns1__MatchCommonPolicyResponse);

	/// Web service operation 'GetAVPolicy' (returns error code or SOAP_OK)
	virtual	int GetAVPolicy_(_ns1__GetAVPolicy *ns1__GetAVPolicy, _ns1__GetAVPolicyResponse *ns1__GetAVPolicyResponse) { return this->GetAVPolicy_(NULL, NULL, ns1__GetAVPolicy, ns1__GetAVPolicyResponse); }
	virtual	int GetAVPolicy_(const char *endpoint, const char *soap_action, _ns1__GetAVPolicy *ns1__GetAVPolicy, _ns1__GetAVPolicyResponse *ns1__GetAVPolicyResponse);

	/// Web service operation 'GetDomesticMatchNormalZRateByID' (returns error code or SOAP_OK)
	virtual	int GetDomesticMatchNormalZRateByID_(_ns1__GetDomesticMatchNormalZRateByID *ns1__GetDomesticMatchNormalZRateByID, _ns1__GetDomesticMatchNormalZRateByIDResponse *ns1__GetDomesticMatchNormalZRateByIDResponse) { return this->GetDomesticMatchNormalZRateByID_(NULL, NULL, ns1__GetDomesticMatchNormalZRateByID, ns1__GetDomesticMatchNormalZRateByIDResponse); }
	virtual	int GetDomesticMatchNormalZRateByID_(const char *endpoint, const char *soap_action, _ns1__GetDomesticMatchNormalZRateByID *ns1__GetDomesticMatchNormalZRateByID, _ns1__GetDomesticMatchNormalZRateByIDResponse *ns1__GetDomesticMatchNormalZRateByIDResponse);

	/// Web service operation 'DetailCreateOrder' (returns error code or SOAP_OK)
	virtual	int DetailCreateOrder_(_ns1__DetailCreateOrder *ns1__DetailCreateOrder, _ns1__DetailCreateOrderResponse *ns1__DetailCreateOrderResponse) { return this->DetailCreateOrder_(NULL, NULL, ns1__DetailCreateOrder, ns1__DetailCreateOrderResponse); }
	virtual	int DetailCreateOrder_(const char *endpoint, const char *soap_action, _ns1__DetailCreateOrder *ns1__DetailCreateOrder, _ns1__DetailCreateOrderResponse *ns1__DetailCreateOrderResponse);

	/// Web service operation 'RTCreateOrder' (returns error code or SOAP_OK)
	virtual	int RTCreateOrder_(_ns1__RTCreateOrder *ns1__RTCreateOrder, _ns1__RTCreateOrderResponse *ns1__RTCreateOrderResponse) { return this->RTCreateOrder_(NULL, NULL, ns1__RTCreateOrder, ns1__RTCreateOrderResponse); }
	virtual	int RTCreateOrder_(const char *endpoint, const char *soap_action, _ns1__RTCreateOrder *ns1__RTCreateOrder, _ns1__RTCreateOrderResponse *ns1__RTCreateOrderResponse);

	/// Web service operation 'GetOrderInfo' (returns error code or SOAP_OK)
	virtual	int GetOrderInfo_(_ns1__GetOrderInfo *ns1__GetOrderInfo, _ns1__GetOrderInfoResponse *ns1__GetOrderInfoResponse) { return this->GetOrderInfo_(NULL, NULL, ns1__GetOrderInfo, ns1__GetOrderInfoResponse); }
	virtual	int GetOrderInfo_(const char *endpoint, const char *soap_action, _ns1__GetOrderInfo *ns1__GetOrderInfo, _ns1__GetOrderInfoResponse *ns1__GetOrderInfoResponse);

	/// Web service operation 'GetInvalidationProviders' (returns error code or SOAP_OK)
	virtual	int GetInvalidationProviders_(_ns1__GetInvalidationProviders *ns1__GetInvalidationProviders, _ns1__GetInvalidationProvidersResponse *ns1__GetInvalidationProvidersResponse) { return this->GetInvalidationProviders_(NULL, NULL, ns1__GetInvalidationProviders, ns1__GetInvalidationProvidersResponse); }
	virtual	int GetInvalidationProviders_(const char *endpoint, const char *soap_action, _ns1__GetInvalidationProviders *ns1__GetInvalidationProviders, _ns1__GetInvalidationProvidersResponse *ns1__GetInvalidationProvidersResponse);

	/// Web service operation 'RefundOrder' (returns error code or SOAP_OK)
	virtual	int RefundOrder_(_ns1__RefundOrder *ns1__RefundOrder, _ns1__RefundOrderResponse *ns1__RefundOrderResponse) { return this->RefundOrder_(NULL, NULL, ns1__RefundOrder, ns1__RefundOrderResponse); }
	virtual	int RefundOrder_(const char *endpoint, const char *soap_action, _ns1__RefundOrder *ns1__RefundOrder, _ns1__RefundOrderResponse *ns1__RefundOrderResponse);

	/// Web service operation 'GetChangeFlightDate' (returns error code or SOAP_OK)
	virtual	int GetChangeFlightDate_(_ns1__GetChangeFlightDate *ns1__GetChangeFlightDate, _ns1__GetChangeFlightDateResponse *ns1__GetChangeFlightDateResponse) { return this->GetChangeFlightDate_(NULL, NULL, ns1__GetChangeFlightDate, ns1__GetChangeFlightDateResponse); }
	virtual	int GetChangeFlightDate_(const char *endpoint, const char *soap_action, _ns1__GetChangeFlightDate *ns1__GetChangeFlightDate, _ns1__GetChangeFlightDateResponse *ns1__GetChangeFlightDateResponse);
};
#endif
